// this will be in layout.tsx 
/* import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <avatars />
        <footer />
      </body>
    </html>
  );
}
*/
"use client";

import { MaskedAvatars } from "@/components/cli-footer/footer";
import { AnimatedTestimonials } from "@/components/cli-footer/testimonials";

export default function MaskedAvatarsDemo() {
    const avatars = [
        { avatar: "https://avatars.githubusercontent.com/u/140585267?v=4", name: "Founder_Shubham" },
        { avatar: "https://avatars.githubusercontent.com/u/175608647?v=4", name: "Founder_Omkar" },
        { avatar: "https://avatars.githubusercontent.com/u/23276437?v=4", name: "Manu Paaji" },
        { avatar: "https://yt3.googleusercontent.com/C25u3DcSguL-wd3GaO110Q1fyO5ClTraTjtF72kJhZtpQwuAv3zLmb7K-ZLJecQQJBVvP1McmA=s900-c-k-c0x00ffffff-no-rj", name: "Harkirat" },
        { avatar: "https://avatars.githubusercontent.com/u/124599?v=4", name: "Shadcn" },
    ];
    const testimonials = [
        {
            quote:
                "Gitfolio has transformed our team's workflow. It's a game-changer for productivity.",
            name: "Shubham Bhilare",
            designation: "Founder of Gitfolio | FolioKit ",
            src: "https://avatars.githubusercontent.com/u/140585267?v=4",
        },
        {
            quote:
                "Not here to showcase but only to code.",
            name: "Omkar Dhumal",
            designation: "Founder of Foliokit | Co-founder of Gitfolio",
            src: "https://avatars.githubusercontent.com/u/175608647?v=4",
        },
        {
            quote:
                "The inspiration for youth to design and animate Ui of nextlevel",
            name: "Manu Paaji",
            designation: "Founder of Aceternity UI",
            src: "https://avatars.githubusercontent.com/u/23276437?v=4",
        },
        {
            quote:
                "The man, the myth, the legend himself of the indian Coding industry ",
            name: "Harkirat Singh",
            designation: "Founder of 100xSchool",
            src: "https://yt3.googleusercontent.com/C25u3DcSguL-wd3GaO110Q1fyO5ClTraTjtF72kJhZtpQwuAv3zLmb7K-ZLJecQQJBVvP1McmA=s900-c-k-c0x00ffffff-no-rj",
        },
        {
            quote:
                "the one who owns the computer",
            name: "Shadcn",
            designation: "founder of Shadcn Ui",
            src: "https://avatars.githubusercontent.com/u/124599?v=4",
        },
    ];
    return (
       <div >
            <AnimatedTestimonials  testimonials={testimonials} />
            <div className="relative flex pt-[100px] w-full items-center justify-around overflow-hidden] ">
                <MaskedAvatars avatars={avatars} />
            </div>
            </div>
    );
}